Fix tests on remove Settings and Extensions
Error:
TypeError: 'isExtensible' on proxy: trap result does not reflect extensibility of proxy target (which is 'true')

Cause: `delete storage[profile]`  not working in "Proxy" element
Configuration elements must not be modified.

https://github.com/microsoft/vscode/issues/80976

Solution: Create a new filtered object, instead of mutate  VSC’s Proxy object